version: "3"

services:
  django:
    container_name: "clerq-django"
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./server:/code/
      - shared:/var/www/
    environment:
      - DJANGO_SETTINGS_MODULE=clerq.settings.prod
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    container_name: clerq-redis
    image: redis:7-bookworm

  nginx:
    container_name: clerq-nginx
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - shared:/var/www/
    image: nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - django
    env_file:
      - .env

volumes:
  shared: