# Generated by Django 4.2.7 on 2023-12-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('APTR', 'Appointing User'), ('APTE', 'Appointee User')], default='APTR', max_length=4),
        ),
    ]
