# Generated by Django 4.2.7 on 2023-12-13 12:45

import appointments.models
from django.conf import settings
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200, verbose_name='appointment subject')),
                ('details', tinymce.models.HTMLField(blank=True, verbose_name='appointment details')),
                ('client_name', models.CharField(max_length=100, verbose_name='client name')),
                ('appointment_date', models.DateField(verbose_name='appointment date')),
                ('appointment_time', models.TimeField(verbose_name='appointment time')),
                ('is_canceled', models.BooleanField(default=False, editable=False, verbose_name='appointment canceled')),
                ('in_progress', models.BooleanField(default=False, editable=False, verbose_name='appointment in progress')),
                ('conclusion_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('conclusion_details', tinymce.models.HTMLField(blank=True, verbose_name='conclusion details')),
                ('appointed_staff', models.ForeignKey(on_delete=models.SET(appointments.models.get_deleted_user), related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='appointed staff')),
                ('appointer_staff', models.ForeignKey(editable=False, on_delete=models.SET(appointments.models.get_deleted_user), related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='appointer staff')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ('appointment_date', '-appointment_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('appointment_date', 'appointment_time'), name='appointment_unique_by_datetime'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('in_progress', True)), fields=('appointed_staff',), name='single_active_appointment_per_appointed_staff'),
        ),
    ]
