# Generated by Django 4.2.7 on 2023-11-28 14:17

import appointments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointed_staff',
            field=models.ForeignKey(default=1, on_delete=models.SET(appointments.models.get_deleted_user), related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='appointed staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointer_staff',
            field=models.ForeignKey(default=1, editable=False, on_delete=models.SET(appointments.models.get_deleted_user), related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='appointer staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(default='John', max_length=100, verbose_name='client name'),
            preserve_default=False,
        ),
    ]
