# Generated by Django 4.2.7 on 2023-11-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_appointee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('appointment_date', 'appointment_time'), 'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_canceled',
            field=models.BooleanField(default=False, editable=False, verbose_name='appointment canceled'),
        ),
    ]
