# Generated by Django 4.2.7 on 2023-12-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appointment_unique_by_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='in_progress',
            field=models.BooleanField(default=False, editable=False, verbose_name='appointment in progress'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('in_progress', True)), fields=('appointed_staff',), name='single_active_appointment_per_appointed_staff'),
        ),
    ]
