# Generated by Django 4.2.7 on 2023-12-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_in_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_concluded',
        ),
    ]
