# Generated by Django 4.2.7 on 2023-12-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_is_concluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_concluded',
            field=models.BooleanField(default=False, editable=False, verbose_name='appointment concluded'),
        ),
    ]
