# Generated by Django 4.2.7 on 2023-12-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointment_is_concluded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('appointment_date', '-appointment_time'), 'verbose_name': 'appointment', 'verbose_name_plural': 'appointments'},
        ),
    ]
